ALTER TYPE appointment_status ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE appointment_status ADD VALUE IF NOT EXISTS 'RESCHEDULE_REQUIRED';
ALTER TYPE appointment_status ADD VALUE IF NOT EXISTS 'REASSIGN_REQUIRED';
ALTER TYPE appointment_status ADD VALUE IF NOT EXISTS 'EXCEPTION';
